"""Onboarding package — re-exports all public symbols for backward compatibility."""

from __future__ import annotations

from telegram_bot import texts

# Re-export skills helpers that tests access via onboarding.<name>
from telegram_bot.services.skills import find_unknown_skills, parse_skills  # noqa: F401

# Main router and all handlers / helpers
from .flow import (
    RESUME_MAX_BYTES,
    _ask_city_tier,
    _ask_domain,
    _ask_grade,
    _ask_role,
    _ask_work_mode,
    _format_upsert_error_message,
    _get_options_for_step,
    _handle_text_selection,
    _merge_profile,
    _process_selection,
    _progress_line,
    _prompt_resume_file,
    _prompt_resume_upload_choice,
    _resume_onboarding,
    _resume_validation_error,
    _save_profile_update,
    _start_new_onboarding,
    _start_settings_flow,
    apply_setting_value,
    build_profile_payload,
    choose_setting_field,
    confirm_skills,
    delete_profile,
    edit_profile,
    edit_skills,
    edit_skills_from_settings,
    format_profile,
    format_skill_confirmation,
    handle_city_tier_text,
    handle_domain_text,
    handle_grade_text,
    handle_resume_choice,
    handle_resume_document,
    handle_resume_non_document,
    handle_role_text,
    handle_work_mode_text,
    keep_profile_from_start,
    open_settings,
    paginate_onboarding_options,
    parse_skills_input,
    restart_onboarding,
    resume_onboarding,
    router,
    select_city_tier,
    select_domain,
    select_grade,
    select_role,
    select_work_mode,
    show_profile,
    start_onboarding,
    start_resume_upload,
    update_profile_from_start,
)

# Keyboard builders
from .keyboards import (
    build_menu_keyboard,
    build_profile_actions_keyboard,
    build_profile_exists_keyboard,
    build_resume_keyboard,
    build_resume_upload_keyboard,
    build_step_keyboard,
    settings_keyboard,
    settings_options_keyboard,
    skills_confirmation_keyboard,
)

# FSM states and constants
from .states import (
    CONFIRM_CALLBACK,
    DEFAULT_CITY_TIERS,
    DEFAULT_DOMAINS,
    DEFAULT_GRADES,
    DEFAULT_ROLES,
    DEFAULT_WORK_MODES,
    EDIT_CALLBACK,
    ONBOARDING_PAGE_SIZE,
    ONBOARDING_STEPS,
    ONBOARDING_TOTAL,
    PROFILE_EDIT_CALLBACK,
    RESUME_SKIP_CALLBACK,
    RESUME_UPLOAD_CALLBACK,
    SETTINGS_FIELD_PREFIX,
    SETTINGS_FIELDS,
    SETTINGS_VALUE_PREFIX,
    START_KEEP_PROFILE_CALLBACK,
    START_RESTART_CALLBACK,
    START_RESUME_CALLBACK,
    START_UPDATE_PROFILE_CALLBACK,
    ProfileOnboarding,
    ProfileSettings,
)

# Validators
from .validators import (
    is_settings_flow,
    load_available_skills,
    match_user_value,
    validate_skills,
)

# Module-level constants that tests reference directly (backward compat)
PROFILE_EXISTS_MESSAGE: str = texts.profile_exists_message()
RESUME_ONBOARDING_MESSAGE: str = texts.resume_onboarding_message()

__all__ = [
    # router
    "router",
    # FSM states
    "ProfileOnboarding",
    "ProfileSettings",
    # constants
    "CONFIRM_CALLBACK",
    "DEFAULT_CITY_TIERS",
    "DEFAULT_DOMAINS",
    "DEFAULT_GRADES",
    "DEFAULT_ROLES",
    "DEFAULT_WORK_MODES",
    "EDIT_CALLBACK",
    "ONBOARDING_PAGE_SIZE",
    "ONBOARDING_STEPS",
    "ONBOARDING_TOTAL",
    "PROFILE_EDIT_CALLBACK",
    "PROFILE_EXISTS_MESSAGE",
    "RESUME_SKIP_CALLBACK",
    "RESUME_UPLOAD_CALLBACK",
    "RESUME_ONBOARDING_MESSAGE",
    "RESUME_MAX_BYTES",
    "SETTINGS_FIELD_PREFIX",
    "SETTINGS_FIELDS",
    "SETTINGS_VALUE_PREFIX",
    "START_KEEP_PROFILE_CALLBACK",
    "START_RESTART_CALLBACK",
    "START_RESUME_CALLBACK",
    "START_UPDATE_PROFILE_CALLBACK",
    # keyboards
    "build_menu_keyboard",
    "build_profile_actions_keyboard",
    "build_profile_exists_keyboard",
    "build_resume_keyboard",
    "build_resume_upload_keyboard",
    "build_step_keyboard",
    "settings_keyboard",
    "settings_options_keyboard",
    "skills_confirmation_keyboard",
    # validators
    "is_settings_flow",
    "load_available_skills",
    "match_user_value",
    "validate_skills",
    # flow handlers (public)
    "apply_setting_value",
    "build_profile_payload",
    "choose_setting_field",
    "confirm_skills",
    "delete_profile",
    "edit_profile",
    "edit_skills",
    "edit_skills_from_settings",
    "format_profile",
    "format_skill_confirmation",
    "handle_city_tier_text",
    "handle_domain_text",
    "handle_grade_text",
    "handle_resume_choice",
    "handle_resume_document",
    "handle_resume_non_document",
    "handle_role_text",
    "handle_work_mode_text",
    "keep_profile_from_start",
    "open_settings",
    "paginate_onboarding_options",
    "parse_skills_input",
    "restart_onboarding",
    "resume_onboarding",
    "select_city_tier",
    "select_domain",
    "select_grade",
    "select_role",
    "select_work_mode",
    "show_profile",
    "start_onboarding",
    "start_resume_upload",
    "update_profile_from_start",
    # flow private helpers (re-exported for test patching)
    "_ask_city_tier",
    "_ask_domain",
    "_ask_grade",
    "_ask_role",
    "_ask_work_mode",
    "_format_upsert_error_message",
    "_get_options_for_step",
    "_handle_text_selection",
    "_merge_profile",
    "_prompt_resume_file",
    "_prompt_resume_upload_choice",
    "_progress_line",
    "_process_selection",
    "_resume_validation_error",
    "_resume_onboarding",
    "_save_profile_update",
    "_start_new_onboarding",
    "_start_settings_flow",
    # skills helpers (re-exported for test access)
    "find_unknown_skills",
    "parse_skills",
]
